### ISSUE TITLE
Wrong link in MELPA

### ISSUE THREAD

**Issue by takaxp** [pzel/weblio#2]
I'm not sure this is the correct space to inform you, but I just found the link in "Homepage" button to this project in MELPA is wrong. The current link is "https://melpa.org/#/weblio.el" but should be corrected to "https://melpa.org/#/weblio". Thanks.

**Comment by pzel** [comment]
Thank you @takaxp, I've updated the weblio package metadata in [this commit](https://github.com/pzel/weblio/commit/ba0b745c3c11a93eaac826f74232f9eefbbae7a1). I believe the melpa package should get regenerated overnight.

Thanks again for letting me know. I hope you find the package useful :)

**Comment by takaxp** [comment]
I realized my message was also wrong because the urls point at melpa.org not github.com, sorry for the confusion. Thank you for the update and I confirmed it, thanks a lot!!
